# Docker Compose for Socat-based Serial-to-TCP Bridge
# Usage:
#   docker compose -f docker-compose-socat.yml up -d    # Start
#   docker compose -f docker-compose-socat.yml logs -f  # View logs
#   docker compose -f docker-compose-socat.yml down     # Stop

services:
  serial-bridge:
    image: socat-bridge
    container_name: serial-bridge
    network_mode: host  # Allows localhost TCP communication
    restart: unless-stopped
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      # Customize these as needed
      - SERIAL_DEVICE=/dev/ttyUSB0
      - BAUD_RATE=115200
      - TCP_PORT=4403
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z 127.0.0.1 4403"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
