name: Build Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src
          file: ./src/Dockerfile
          push: false
          load: true
          tags: meshtastic-serial-bridge:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify image was built
        run: |
          docker images | grep meshtastic-serial-bridge
